services:
  postgres:
    image: postgres:16
    container_name: boi_forte_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - boi-forte-network

  app:
    build: .
    container_name: boi_forte_api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '${PORT}:${PORT}'
    environment:
      DATABASE_URL: ${DATABASE_URL}
  
    networks:
      - boi-forte-network
    restart: unless-stopped

  prisma-studio:
    image: node:18
    depends_on:
      - postgres
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npx prisma studio
    ports:
      - '${PRISMA_PORT}:${PRISMA_PORT}'
    environment:
      DATABASE_URL:

volumes:
  postgres_data:

networks:
  boi-forte-network:
    driver: bridge
